### ISSUE TITLE
您好，请问良辰吉日选定在什么时候，我非常关注您的项目！

### ISSUE THREAD

**Issue by Debug-boy** [abcz316/linuxKernelProcInjector#2]

**Comment by abcz316** [comment]
This project is going to be a long, long, long time

**Comment by Debug-boy** [comment]
祝项目顺利进行

**Comment by abcz316** [comment]
This project has been fully developed and completed. I am still waiting for an opportunity, and I will make it public when the time is ripe. It is not a good time for a long time now
